services:
  traefik:
    image: traefik:v3
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"

      - "--entrypoints.web.address=:80"

      - "--api.insecure=true"
      - "--log.level=DEBUG"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/dynamic:/etc/traefik/dynamic:ro"
    networks:
      - cla321-network
      - k3d-dev

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=cla321-network"
      - "traefik.http.routers.gitlab.rule=Host(`gitlab.localhost`)"
      - "traefik.http.routers.gitlab.entrypoints=web"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"

    ports:
      - "2222:22"

    environment:
      TZ: Australia/Sydney

      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.localhost'
        
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        
        puma['worker_processes'] = 2
        sidekiq['concurrency'] = 4
        
        letsencrypt['enable'] = false

    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

    shm_size: "256m"

    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "--silent",
          "http://localhost/-/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 5m

    networks:
      cla321-network:
        aliases:
         - gitlab.localhost

  gitlab_runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab_runner

    depends_on:
      gitlab:
        condition: service_healthy

    environment:
      TZ: Australia/Sydney

    volumes:
      - gitlab-runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - cla321-network

networks:
  cla321-network:
    name: cla321-network

  k3d-dev:
    external: true
    name: k3d-dev

volumes:
  gitlab-runner-config:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
